/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WebviewOptions {
  url: string
  width: number
  height: number
}
export declare function createWebview(options: WebviewOptions): void
